services:
  postgres:
    image: postgres
    container_name: otp-pg
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - otp_data:/var/lib/postgresql

volumes:
  otp_data: 
    name: otp_data